version: '3.7'

services:
  web:
    image: nginx:1.14
    working_dir: /app
    volumes:
      - ./app:/app
      - ./dockerfiles/site.info:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:8000
    links:
      - app

  app:
#    build:
#      context: ./dockerfiles
#      dockerfile: app.dockerfile
    image: adnan/php:2.0.0
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB_HOST: db
      POSTGRES_DB_PORT: 5432
      MONGO_DB_HOST: mongo
      MONGO_DB_PORT: 27017
      REDIS_HOST: redis
#    user: 1000:1001
    links:
      - db
      - node
  db:
    image: postgres:10.5
    environment:
      POSTGRES_USER: homestead
      POSTGRES_PASS: secret
      POSTGRES_DATABASE: homestead

  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: homestead
      MONGO_INITDB_ROOT_PASSWORD: secret

  mongo-express:
    image: mongo-express
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: homestead
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo

  adminer:
    image: adminer
    ports:
      - 8083:8080

  node:
    image: node:12.4
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
    links:
      - redis
    working_dir: /app
    volumes:
      - ./app/node:/app

  redis:
    container_name: redis
    image: redis:5.0
